[build]
publish = "./exampleSite/public/"
command = "npm run deploy"

[context.production]
[context.production.environment]
HUGO_VERSION = "0.135.0"
HUGO_ENV = "production"
GO_VERSION = "1.23"
NODE_ENV = "development"
